version: 2

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/YewFence/gpg-unlock/cmd.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - repository:
      owner: YewFence
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/YewFence/gpg-unlock"
    description: "Fetch GPG passphrase from your password manager and inject into gpg-agent cache"
    directory: Formula
    license: "MIT"
    install: |
      bin.install "gpg-unlock"
