services:
  dev:
    image: golang:1.24
    working_dir: /src
    volumes:
      - .:/src
    command: ["sleep", "infinity"]

  build:
    image: goreleaser/goreleaser:latest
    working_dir: /src
    volumes:
      - .:/src
    command: ["build", "--snapshot", "--clean"]

  release-snapshot:
    image: goreleaser/goreleaser:latest
    working_dir: /src
    volumes:
      - .:/src
    command: ["release", "--snapshot", "--skip=publish", "--clean"]
